### ISSUE TITLE
[1.19.2] crash on server startup

### ISSUE THREAD

**Issue by BugmanBugman** [baguchan/WealthyAndGrowth#1]
https://gist.github.com/BugmanBugman/c19f4535d4b1e49dfd6b3539d1e5de48

**Comment by baguchi** [comment]
Have you tried Wealthy And Growth without another mod?

**Comment by BugmanBugman** [comment]
Not sure which mod it could be, but i tried it without that one.
https://gist.github.com/BugmanBugman/aada3e8837dd79cab5935ff2d7284646

**Comment by baguchi** [comment]
oh wait I know that situation.
It's my import problem happen different java program sorry.
I'll fix in 1.0.1
